source 'https://rubygems.org'

gem 'rake'
gem 'activerecord', :require => "active_record"
gem 'sqlite3'

gem 'sinatra', '>= 1.3.3'
gem 'json'
gem 'rabl', :path => File.expand_path(File.dirname(__FILE__) + "/../../")

# Test requirements
gem 'riot', :group => "test"
gem 'rack-test', :require => "rack/test", :group => "test"
