source 'https://rubygems.org'

# Project requirements
gem 'rake'

# Component requirements
gem 'activerecord', :require => "active_record"
gem 'sqlite3'

# Test requirements
gem 'riot', :group => "test"
gem 'rack-test', :require => "rack/test", :group => "test"

# Padrino
gem 'padrino', '~> 0.10.7'
gem 'json'
gem 'rabl', :path => File.expand_path(File.dirname(__FILE__) + "/../../")
