source 'https://rubygems.org'

gem "rails", "~> 2.3.18"
gem "sqlite3", :require => "sqlite3"
gem 'json'
gem 'rabl', :path => File.expand_path(File.dirname(__FILE__) + "/../../")
gem 'rake', "~> 0.9.2.2"

gem 'riot', :group => "test"
gem 'rack-test', :require => "rack/test", :group => "test"
