source :gemcutter
gem "rails", "~> 2.3.14"
gem "sqlite3", :require => "sqlite3"
gem 'json'
gem 'rabl', :path => File.expand_path(File.dirname(__FILE__) + "/../../")

gem 'riot', :group => "test"
gem 'rack-test', :require => "rack/test", :group => "test"
