# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'

require 'tasks/rails'

Rake::TestTask.new("test:rabl") do |test|
  test.pattern = "test/functionals/**/*_test.rb"
  test.verbose = true
end