# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
require 'rake/testtask'

Rails.application.load_tasks

Rake::TestTask.new("test:rabl") do |test|
  test.pattern = "test/controllers/**/*_test.rb"
  test.verbose = true
  test.warning = false
end
